name: Cocoapods

on: [push]

jobs:
  StorybookKit:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: "13.2"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods
        run: pod lib lint StorybookKit.podspec --allow-warnings
  StorybookUI:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: "13.2"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods
        run: pod lib lint --include-podspecs=StorybookKit.podspec StorybookUI.podspec --allow-warnings
  StorybookKitTextureSupport:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: "13.2"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods
        run: pod lib lint --include-podspecs=StorybookKit.podspec StorybookKitTextureSupport.podspec --allow-warnings
